name: Update Pokemon in README

on:
  schedule:
    - cron: "*/5 * * * *"  # 5분마다 실행 (UTC 기준)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Run todays_pokemon.py
        run: |
          pip install requests
          python todays_pokemon.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main
          git add README.md
          git commit -m "자동 업데이트: 오늘의 포켓몬 정보 갱신" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
